[project]
name = "peppol-demo"
version = "0.1.0"
description = "Simple Peppol invoice demo using Recommand API"
dependencies = [
    "requests>=2.25.0",
]
requires-python = ">=3.8"

[project.scripts]
demo = "demo_peppol_invoice:main"